dependencies:
# ======== PostgreSQL ===========
- name: postgres-stash
  version: 9.6
  repository: "@appscode"
  alias: postgres-stash-9-6
- name: postgres-stash
  version: 10.2
  repository: "@appscode"
  alias: postgres-stash-10-2
- name: postgres-stash
  version: 10.6
  repository: "@appscode"
  alias: postgres-stash-10-6
- name: postgres-stash
  version: 11.1
  repository: "@appscode"
  alias: postgres-stash-11-1
- name: postgres-stash
  version: 11.2
  repository: "@appscode"
  alias: postgres-stash-11-2
# ======== MongoDB ==============
# ======== MySQL ================
# ======== Percona ==============
# ======== MariaDB ==============
# ======== Elasticsearch ========
# ======== Cluster ==============
# ========  PVC =================
