apiVersion: v1
description: 'postgres-catalog by AppsCode - PostgreSQL database backup and restore plugin for Stash'
name: postgres-catalog
version: 0.1.0
appVersion: 0.1.0
home: https://github.com/stashed/postgres
icon: https://cdn.appscode.com/images/icon/stash.png
sources:
  - https://github.com/stashed/postgres
maintainers:
  - name: appscode
    email: support@appscode.com
